
import { CommonModule, registerLocaleData } from '@angular/common';
import {NgModule, LOCALE_ID} from '@angular/core';
import { MatMomentDateModule } from "@angular/material-moment-adapter";
import { CdkTableModule, CdkCell, CdkColumnDef, CdkCellDef, CdkColumnDefBase } from "@angular/cdk/table";
import { CdkTreeModule } from "@angular/cdk/tree";
import { ScrollingModule } from "@angular/cdk/scrolling";
import {DragDropModule} from '@angular/cdk/drag-drop';
import { FlexLayoutModule } from '@angular/flex-layout';
import localeHe from '@angular/common/locales/he'; 
registerLocaleData(localeHe);
import {
  MatAutocompleteModule,
  MatBadgeModule,
  MatBottomSheetModule,
  MatButtonModule,
  MatButtonToggleModule,
  MatCardModule,
  MatCheckboxModule,
  MatChipsModule,
  MatDatepickerModule,
  MatDialogModule,
  MatDividerModule,
  MatExpansionModule,
  MatGridListModule,
  MatIconModule,
  MatInputModule,
  MatListModule,
  MatMenuModule,
  MatNativeDateModule,
  MatPaginatorModule,
  MatProgressBarModule,
  MatProgressSpinnerModule,
  MatRadioModule,
  MatRippleModule,
  MatSelectModule,
  MatSidenavModule,
  MatSliderModule,
  MatSlideToggleModule,
  MatSnackBarModule,
  MatSortModule,
  MatStepperModule,
  MatTableModule,
  MatTabsModule,
  MatToolbarModule,
  MatTooltipModule,
  MatTreeModule,
  MatFormFieldModule,
  MatOptionModule,
  DateAdapter,
  MatIconRegistry,
  MAT_SNACK_BAR_DEFAULT_OPTIONS,
} from '@angular/material';
import { BidiModule } from '@angular/cdk/bidi';

@NgModule({
      imports: [
        FlexLayoutModule,
        MatProgressSpinnerModule,
        MatPaginatorModule,
        MatExpansionModule,
        MatDialogModule,
        MatButtonModule,
        MatIconModule,
        MatCardModule,
        MatFormFieldModule,
        MatInputModule,
        MatListModule,
        MatDatepickerModule,
        MatNativeDateModule,
        MatMomentDateModule,
        MatSelectModule,
        MatOptionModule,
        MatCheckboxModule,
        MatAutocompleteModule,
        MatRadioModule,
        MatTableModule,
        BidiModule,
        
        //FlexLayoutModule,
      ],
      exports: [
        FlexLayoutModule,
        MatProgressSpinnerModule,
        MatExpansionModule,
        MatDialogModule,
        MatButtonModule,
        MatIconModule,
        MatCardModule,
        MatFormFieldModule,
        MatInputModule,
        MatListModule,
        MatDatepickerModule,
        MatNativeDateModule,
        MatMomentDateModule,
        MatSelectModule,
        MatOptionModule,
        MatCheckboxModule,
        MatRadioModule,
        MatAutocompleteModule,
        MatTableModule,
        MatPaginatorModule,
        CdkTableModule,
        CdkTreeModule,
        DragDropModule,
        MatAutocompleteModule,
        MatBadgeModule,
        MatBottomSheetModule,
        MatButtonModule,
        MatButtonToggleModule,
        MatCardModule,
        MatCheckboxModule,
        MatChipsModule,
        MatStepperModule,
        MatDatepickerModule,
        MatDialogModule,
        MatDividerModule,
        MatExpansionModule,
        MatGridListModule,
        MatIconModule,
        MatInputModule,
        MatListModule,
        MatMenuModule,
        MatNativeDateModule,
        MatPaginatorModule,
        MatProgressBarModule,
        MatProgressSpinnerModule,
        MatRadioModule,
        MatRippleModule,
        MatSelectModule,
        MatSidenavModule,
        MatSliderModule,
        MatSlideToggleModule,
        MatSnackBarModule,
        MatSortModule,
        MatTableModule,
        MatTabsModule,
        MatToolbarModule,
        MatTooltipModule,
        MatTreeModule,
        ScrollingModule,
        BidiModule,
        //FlexLayoutModule,
      ],
      providers:[
        CdkColumnDef,
        CdkCell,
        CdkCellDef,
        CdkColumnDefBase,
        {
          provide: LOCALE_ID,
          useValue: 'he-IL' // 'de-DE' for Germany, 'fr-FR' for France ...
        },
        {provide: MAT_SNACK_BAR_DEFAULT_OPTIONS, useValue: {horizontalPosition:'left',duration: 10000}}]
    })
export class MaterialModule {
  constructor(private dateAdapter:DateAdapter<any>) {
    this.dateAdapter.setLocale('he-IL');
  }
}
